name: macOS console build

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  macos:
    name: ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      - name: Extract architecture
        id: architecture
        run: echo "ARCH=$(uname -m)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.8.2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: backend/poetry.lock
      - name: Select Python interpreter
        working-directory: backend
        run: poetry env use "$pythonLocation/bin/python"
      - name: Install dependencies
        working-directory: backend
        run: poetry install
      - name: Run tests
        working-directory: backend
        run: poetry run pytest
      - name: Package console application
        working-directory: backend
        run: poetry run pyinstaller spec_files/cli_app/NiimStudio.spec --noconfirm --clean
      - name: Smoke-test executable
        working-directory: backend
        run: dist/niimstudio --help
      - name: Create archive
        working-directory: backend
        run: tar -C dist -czf "NiimStudio-CLI-${{ steps.version.outputs.VERSION }}-macOS-${{ steps.architecture.outputs.ARCH }}.tar.gz" niimstudio
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: NiimStudio-CLI-${{ steps.version.outputs.VERSION }}-macOS-${{ steps.architecture.outputs.ARCH }}.tar.gz
          path: backend/NiimStudio-CLI-${{ steps.version.outputs.VERSION }}-macOS-${{ steps.architecture.outputs.ARCH }}.tar.gz
          retention-days: 1
